#pragma once

enum eControllerType {
    CONTROLLER_KEYBOARD,
    CONTROLLER_OPTIONAL_EXTRA_KEY,
    CONTROLLER_MOUSE,
    CONTROLLER_JOY_STICK,

    CONTROLLER_COUNT
};

constexpr eControllerType CONTROLLER_TYPES_ALL[CONTROLLER_COUNT] = { CONTROLLER_KEYBOARD, CONTROLLER_OPTIONAL_EXTRA_KEY, CONTROLLER_MOUSE, CONTROLLER_JOY_STICK };
constexpr eControllerType CONTROLLER_TYPES_KEYBOARD[]            = { CONTROLLER_KEYBOARD, CONTROLLER_OPTIONAL_EXTRA_KEY };
