#pragma once

enum eControllerType {
    CONTROLLER_KEYBOARD1,
    CONTROLLER_KEYBOARD2, // OPTIONAL_EXTRA_KEY
    CONTROLLER_MOUSE,
    CONTROLLER_PAD,


    CONTROLLER_NUM
};

constexpr eControllerType CONTROLLER_TYPES_ALL[CONTROLLER_NUM] = { CONTROLLER_KEYBOARD1, CONTROLLER_KEYBOARD2, CONTROLLER_MOUSE, CONTROLLER_PAD };
constexpr eControllerType CONTROLLER_TYPES_KEYBOARD[]          = { CONTROLLER_KEYBOARD1, CONTROLLER_KEYBOARD2 };
