blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Updated-Classic/gta-reversed-modern/discussions
    about: Please ask and answer questions here.
