include(ExternalProject)
set(OGG_SOURCE_DIR "${CMAKE_SOURCE_DIR}/vendor/ogg")
set(OGG_PREFIX "${CMAKE_BINARY_DIR}/vendor_ogg")
set(OGG_INSTALL_PREFIX "${OGG_PREFIX}/install/$<CONFIG>")
set(OGG_ARGS
        "-DCMAKE_INSTALL_PREFIX=${OGG_INSTALL_PREFIX}"
        "-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}"
        "-DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}"
        "-DCMAKE_CXX_FLAGS_MINSIZEREL=${CMAKE_CXX_FLAGS_MINSIZEREL}"
        "-DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}"
        "-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}"
        "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}"
        "-DCMAKE_C_FLAGS_DEBUG=${CMAKE_C_FLAGS_DEBUG}"
        "-DCMAKE_C_FLAGS_MINSIZEREL=${CMAKE_C_FLAGS_MINSIZEREL}"
        "-DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}"
        "-DCMAKE_C_FLAGS_RELWITHDEBINFO=${CMAKE_C_FLAGS_RELWITHDEBINFO}")
if(MSVC)
    list(APPEND OGG_ARGS 
        "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
        "-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS} /MP")
endif()
ExternalProject_Add(
    ogg_external
    PREFIX ${OGG_PREFIX}
    SOURCE_DIR ${OGG_SOURCE_DIR}
    CMAKE_ARGS ${OGG_ARGS}
)
set_target_properties(ogg_external PROPERTIES FOLDER "Vendor")
add_library(ogg INTERFACE)
target_link_libraries(ogg INTERFACE "${OGG_INSTALL_PREFIX}/lib/ogg.lib")
target_include_directories(ogg INTERFACE "${OGG_INSTALL_PREFIX}/include")
add_dependencies(ogg ogg_external)
