name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Configure
        shell: cmd
        run: cmake -Bbuild -H. -A Win32 -DGTASA_UNITY_BUILD=1

      - name: Build Debug
        shell: cmd
        run: cmake --build build --config Debug

      - name: Artifact Debug
        uses: actions/upload-artifact@v3
        with:
          name: gta_reversed-debug
          path: bin/Debug

      - name: Build Release
        run: cmake --build build --config Release

      - name: Artifact Release
        uses: actions/upload-artifact@v3
        with:
          name: gta_reversed-release
          path: bin/Release
