name: Build

env:
    CL: /MP
    build: '${{ github.workspace }}/build'

on: [ push, pull_request ]

permissions:
    contents: read

jobs:
    build:
        permissions:
            contents: read
            security-events: write

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ windows-2022 ]
                arch: [ x86 ]
                conf: [ Debug, Release ]

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true
              
            - name: Initialize submodules
              run: |
                git submodule update --init --recursive --remote

            - name: Install CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: cpp

            - name: Configure ${{ matrix.arch }}
              shell: cmd
              run: cmake -B ${{ env.build }} -H. -A Win32

            - name: Build ${{ matrix.conf }}
              shell: cmd
              run: cmake --build build --config ${{ matrix.conf }}

            - name: Upload artifacts for ${{ matrix.conf }}-${{ matrix.arch }}
              uses: actions/upload-artifact@v4
              with:
                  name: gta_reversed-${{ matrix.conf }}
                  path: bin/${{ matrix.conf }}

            - name: CodeQL Analysis
              id: run-analysis
              shell: bash
              run: |
                  "${{ github.workspace }}/codeql/codeql" database create codeql-db --language=cpp --source-root .
                  # Rebuild within the CodeQL database
                  cmake -B ${{ env.build }} -H. -A Win32
                  cmake --build build --config ${{ matrix.conf }}
                  codeql database finalize codeql-db
                  # Analyze and produce SARIF
                  "${{ github.workspace }}/codeql/codeql" database analyze codeql-db --format=sarif-latest --output=analysis.sarif
                  echo "sarif=analysis.sarif" >> $GITHUB_OUTPUT

            - name: Upload SARIF to GitHub
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: ${{ steps.run-analysis.outputs.sarif }}
