name: Build

env:
    # Compile in parallel where possible.
    CL: /MP

    # Path to the CMake build directory.
    build: '${{ github.workspace }}/build'

# Triggers the workflow on push or pull request events for all branches.
on: [ push, pull_request ]

permissions:
    contents: read

jobs:
    build:
        permissions:
            contents: read # for actions/checkout to fetch code
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ windows-2022 ]
                arch: [ x86 ]
                conf: [ Debug, Release ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
                    submodules: recursive

            -   name: Initialize CodeQL
                uses: github/codeql-action/init@v3
                with:
                    languages: cpp
                    queries: security-and-quality

            -   name: Configure ${{ matrix.arch }}
                shell: cmd
                run: cmake -B ${{ env.build }} -H. -A Win32 # ${{ matrix.arch }}

            -   name: Build ${{ matrix.conf }}
                shell: cmd
                run: cmake --build build --config ${{ matrix.conf }}

            -   name: Perform CodeQL Analysis
                uses: github/codeql-action/analyze@v3
                with:
                    category: "/language:cpp"
                    upload: true
                    wait-for-processing: true

            -   name: Upload artifacts for ${{ matrix.conf }}-${{ matrix.arch }}
                uses: actions/upload-artifact@v4
                with:
                    name: gta_reversed-${{ matrix.conf }}
                    path: bin/${{ matrix.conf }}
