#pragma once

#include "Enums/eModelID.h"
#include <Audio/Enums/eAEVehicleSoundType.h>
#include <Audio/Enums/eAEVehicleAudioTypeForName.h>
#include <Audio/Enums/eAEVehicleAudioType.h>
#include <Audio/Enums/eAERadioType.h>
#include <SoundIDs.h>

//!  
enum class eAEVehicleHornType : int8 {
    NONE      = -1,
    BIKE      = SND_GENRL_HORN_BIKEBELL, // 1

    ESCORT    = SND_GENRL_HORN_ESCORTHORN,  // 1
    CHEVY56   = SND_GENRL_HORN_HORN56CHEV,  // 2
    BMW328    = SND_GENRL_HORN_HORNBMW328,  // 3
    BUS_A     = SND_GENRL_HORN_HORNBUS,     // 4
    BUS_B     = SND_GENRL_HORN_HORNBUS2,    // 5
    JEEP      = SND_GENRL_HORN_HORNJEEP,    // 6
    PICKUP    = SND_GENRL_HORN_HORNPICKUP,  // 7
    PORSCHE   = SND_GENRL_HORN_HORNPORSCHE, // 8
    TRUCK     = SND_GENRL_HORN_HORNTRUCK,   // 9
    CAR_FIRST = ESCORT,                     // 1
    CAR_LAST  = TRUCK,                      // 9

    NUM // 10
};

struct tVehicleAudioSettings {
    eAEVehicleSoundType        VehicleAudioType{};
    eSoundBankS16              PlayerBank{}; //!< Bank used when the player *is* in the vehicle
    eSoundBankS16              DummyBank{};  //!< Bank used when the player *is not* in the vehicle
    int8                       BassSetting{};
    float                      BassFactor{};
    float                      EnginePitch{};
    eAEVehicleHornType         HornType{}; //!< Actually just the sound ID
    float                      HornPitch{};
    uint8                      DoorType{};      //!< [UNUSED?] Number of doors most likely (Thus the enum could be removed?) - `-1` used if no doors
    uint8                      EngineUpgrade{}; //!< [UNUSED?] No clue
    eRadioID                   RadioStation{};
    eAERadioType               RadioType{};
    eAEVehicleAudioTypeForName VehicleAudioTypeForName{};
    float                      EngineVolumeOffset{}; //!< Engine's base volume

public:
    [[nodiscard]] bool IsHeli()                const { return VehicleAudioType == eAEVehicleSoundType::AE_AIRCRAFT_HELICOPTER; }
    [[nodiscard]] bool IsPlane()               const { return VehicleAudioType == eAEVehicleSoundType::AE_AIRCRAFT_PLANE; }
    [[nodiscard]] bool IsPlaneOrHeli()         const { return IsPlane() || IsHeli(); }
    [[nodiscard]] bool IsSeaplane()            const { return VehicleAudioType == eAEVehicleSoundType::AE_AIRCRAFT_SEAPLANE; }
    [[nodiscard]] bool IsAircraftEngineSound() const { return notsa::contains({AE_AIRCRAFT_HELICOPTER, AE_AIRCRAFT_PLANE, AE_AIRCRAFT_SEAPLANE}, VehicleAudioType); }
    [[nodiscard]] bool IsCar()                 const { return VehicleAudioType == eAEVehicleSoundType::AE_CAR; }
    [[nodiscard]] bool IsBike()          const { return VehicleAudioType == eAEVehicleSoundType::AE_BIKE; }
    [[nodiscard]] bool IsCarEngineSound()      const { return notsa::contains({eAEVehicleSoundType::AE_BIKE, eAEVehicleSoundType::AE_CAR}, VehicleAudioType); }
    [[nodiscard]] bool IsBMX()                 const { return VehicleAudioType == eAEVehicleSoundType::AE_BMX; }
};
VALIDATE_SIZE(tVehicleAudioSettings, 0x24);

// 0x860AF0
// Array not marked as `constexpr` so that it can be edited by the debug tool
// Order of entries is the same as the model IDs (Starting at 400 - LANDSTAL)
#pragma warning(push)
#pragma warning(disable : 4305) // truncation from 'double' to 'float'
inline std::array<tVehicleAudioSettings, 232> VehicleAudioSettings{{
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PICKUP, 1.f, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 1.1892071, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_COBRA_P, SND_BANK_GENRL_COBRA_D, 1, 0.9f, 1.f, eAEVehicleHornType::CHEVY56, 1.0594631, 2, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.0, 1.f, eAEVehicleHornType::TRUCK, 0.84089643, 3, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_RIG, 6.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 1, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_STATION_WAGON, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.85f, 1.f, eAEVehicleHornType::BMW328, 0.9438743, 2, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.7f, 0.84089643, eAEVehicleHornType::BUS_A, 0.79370052, 3, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_TRUCK, 6.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 0.8908987, 3, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_FIRETRUCK, 5.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_B, 0.8908987, 3, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_GARBAGE_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.85f, 1.f, eAEVehicleHornType::CHEVY56, 1.f, 2, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_STRETCH, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::ESCORT, 1.0594631, 1, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_COBRA_P, SND_BANK_GENRL_COBRA_D, 1, 0.9f, 1.f, eAEVehicleHornType::PORSCHE, 1.122462, 2, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 1.f, 1.f, eAEVehicleHornType::CHEVY56, 1.122462, 1, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.77999997, 1.f, eAEVehicleHornType::CHEVY56, 1.2599211, 4, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.7f, 1.3348398, eAEVehicleHornType::PICKUP, 0.9438743, 4, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_VAN, 5.0},
    {AE_CAR, SND_BANK_GENRL_PORSCHE_P, SND_BANK_GENRL_PORSCHE_D, 1, 0.9f, 1.f, eAEVehicleHornType::PORSCHE, 1.f, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::PICKUP, 0.9438743, 4, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_AMBULANCE, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_APACHE, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::ESCORT, 0.8908987, 4, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 1.0594631, 1, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.85f, 1.f, eAEVehicleHornType::BUS_B, 1.122462, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_TAXI, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::BMW328, 0.8908987, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PICKUP, 1.f, 4, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_PICK_UP, 0.0},
    {AE_CAR, SND_BANK_GENRL_ICEVAN_P, SND_BANK_GENRL_VW_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_B, 0.9438743, 4, 0, RADIO_OFF, AE_RT_CIVILIAN, AE_VAT_ICE_CREAM_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_HOTROD_P, SND_BANK_GENRL_HOTROD_D, 0, 0.9f, 1.f, eAEVehicleHornType::JEEP, 0.8908987, -1, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_BUGGY, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_APACHE, SND_BANK_UNK, 0, 0.85f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PORSCHE, 1.f, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.3348398, eAEVehicleHornType::TRUCK, 1.122462, 3, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 0.8908987, 4, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_PORSCHE_P, SND_BANK_GENRL_PORSCHE_D, 1, 1.f, 1.f, eAEVehicleHornType::BMW328, 1.0594631, 2, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUS_P, SND_BANK_GENRL_BUS_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_B, 0.84089643, -1, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_COACH, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.9f, 1.f, eAEVehicleHornType::TRUCK, 0.8908987, 3, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_TANK, 6.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.f, eAEVehicleHornType::TRUCK, 0.9438743, 3, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_HOTROD_P, SND_BANK_GENRL_HOTROD_D, 0, 0.7f, 1.f, eAEVehicleHornType::BMW328, 1.122462, 1, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_BUGGY, 0.0},
    {AE_SPECIAL, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.77999997, 1.f, eAEVehicleHornType::ESCORT, 0.8908987, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUS_P, SND_BANK_GENRL_BUS_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_B, 0.8908987, -1, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_COACH, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BUS_A, 1.0594631, 1, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_TAXI, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 0.85f, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_CONVERTIBLE, 0.0},
    {AE_CAR, SND_BANK_GENRL_VW_VAN_P, SND_BANK_GENRL_VW_VAN_D, 0, 0.77999997, 1.f, eAEVehicleHornType::ESCORT, 0.84089643, 4, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_CHAINSAW_P, SND_BANK_GENRL_SCOOTER_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.9f, 1.f, eAEVehicleHornType::BUS_B, 1.122462, 4, 0, RADIO_OFF, AE_RT_CIVILIAN, AE_VAT_HEARSE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.77999997, 1.f, eAEVehicleHornType::TRUCK, 1.f, 3, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_TRUCK, 6.0},
    {AE_CAR, SND_BANK_GENRL_HEAVY_V8_P, SND_BANK_GENRL_HEAVY_V8_D, 0, 0.9f, 1.f, eAEVehicleHornType::TRUCK, 1.0594631, 2, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_MONSTER_TRUCK, 6.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.85f, 1.f, eAEVehicleHornType::BMW328, 1.f, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_R22, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_BIKE, SND_BANK_GENRL_SCOOTER_P, SND_BANK_GENRL_SCOOTER_D, 2, 1.f, 1.f, eAEVehicleHornType::ESCORT, 1.0594631, -1, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_MOPED, 0.0},
    {AE_TRAIN, SND_BANK_GENRL_TRAIN_P, SND_BANK_GENRL_TRAM_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_TRAM, 0.0},
    {AE_SPECIAL, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_PORSCHE_P, SND_BANK_GENRL_PORSCHE_D, 1, 0.9f, 1.f, eAEVehicleHornType::PORSCHE, 1.f, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 2, 0.85f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 2, 0.85f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.f, eAEVehicleHornType::TRUCK, 0.9438743, 3, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_VW_VAN_P, SND_BANK_GENRL_VW_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 0.9438743, 3, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_GOLF_P, SND_BANK_GENRL_GOLF_D, 2, 0.9f, 1.f, eAEVehicleHornType::ESCORT, 1.2599211, -1, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_GOLF_CART, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BMW328, 1.122462, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_STATION_WAGON, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.85f, 1.f, eAEVehicleHornType::CHEVY56, 1.0594631, 4, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_SINGLEPROP, SND_BANK_GENRL_FASTPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_SEA_PLANE, 0.0},
    {AE_BIKE, SND_BANK_GENRL_SPORTSBIKE_P, SND_BANK_GENRL_SPORTSBIKE_D, 2, 0.7f, 1.1892071, eAEVehicleHornType::JEEP, 1.122462, -1, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_BIKE, SND_BANK_GENRL_SCOOTER_P, SND_BANK_GENRL_SCOOTER_D, 2, 1.f, 1.f, eAEVehicleHornType::ESCORT, 1.0594631, -1, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_MOPED, 0.0},
    {AE_BIKE, SND_BANK_GENRL_VTWINBIKE_P, SND_BANK_GENRL_VTWINBIKE_D, 2, 0.65f, 1.f, eAEVehicleHornType::ESCORT, 0.84089643, -1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_RC_CAR_P, SND_BANK_GENRL_RC_CAR_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_RC_HELI_P, SND_BANK_GENRL_RC_HELI_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_BELAIR_P, SND_BANK_GENRL_BELAIR_D, 0, 0.85f, 1.f, eAEVehicleHornType::BUS_B, 0.9438743, 1, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BELAIR_P, SND_BANK_GENRL_BELAIR_D, 0, 0.77999997, 1.f, eAEVehicleHornType::CHEVY56, 1.f, 1, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_BIKE, SND_BANK_GENRL_DIRTBIKE_P, SND_BANK_GENRL_DIRTBIKE_D, 2, 0.85f, 1.f, eAEVehicleHornType::JEEP, 0.8908987, -1, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_R22, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.9f, 1.1892071, eAEVehicleHornType::TRUCK, 1.2599211, 4, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_DIRTBIKE_P, SND_BANK_GENRL_DIRTBIKE_D, 2, 0.30000001, 1.f, eAEVehicleHornType::ESCORT, 1.f, -1, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_QUADBIKE, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_BOAT, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 2, 0.9f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_DINGHY, 0.0},
    {AE_CAR, SND_BANK_GENRL_CADILLAC_P, SND_BANK_GENRL_CADILLAC_D, 0, 1.f, 1.f, eAEVehicleHornType::BUS_A, 1.0594631, 1, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 0.85f, 1.f, eAEVehicleHornType::PORSCHE, 0.9438743, 1, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_FASTPROP, SND_BANK_GENRL_FASTPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 1, 0.9f, 1.f, eAEVehicleHornType::BMW328, 1.122462, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MODEL_T_P, SND_BANK_GENRL_MODEL_T_D, 0, 0.65f, 1.f, eAEVehicleHornType::CHEVY56, 0.9438743, 4, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_PICK_UP, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.65f, 1.f, eAEVehicleHornType::PICKUP, 1.1892071, 2, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_STATION_WAGON, 0.0},
    {AE_CAR, SND_BANK_GENRL_PORSCHE_P, SND_BANK_GENRL_PORSCHE_D, 1, 0.9f, 1.f, eAEVehicleHornType::PORSCHE, 1.122462, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_BMX, SND_BANK_GENRL_BICYCLE_P, SND_BANK_GENRL_BICYCLE_D, 2, 0.7f, 1.f, eAEVehicleHornType::BIKE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_BICYCLE, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 4, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_VW_VAN_P, SND_BANK_GENRL_VW_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 1.122462, 4, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_CAMPER_VAN, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_CAR, SND_BANK_GENRL_AIRPORT_P, SND_BANK_GENRL_AIRPORT_D, 2, 1.f, 1.f, eAEVehicleHornType::ESCORT, 1.122462, -1, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_MODEL_T_P, SND_BANK_GENRL_MODEL_T_D, 0, 0.7f, 1.f, eAEVehicleHornType::TRUCK, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_BULLDOZER, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_MAVERICK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_MAVERICK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.85f, 1.f, eAEVehicleHornType::BUS_B, 0.9438743, 2, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_B, 1.f, 2, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::BMW328, 0.9438743, 2, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.85f, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 2, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 1, 0.85f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_BOAT, 0.0},
    {AE_CAR, SND_BANK_GENRL_COBRA_P, SND_BANK_GENRL_COBRA_D, 0, 0.9f, 1.f, eAEVehicleHornType::BMW328, 1.122462, 2, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.7f, 1.1892071, eAEVehicleHornType::BUS_B, 0.9438743, 2, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PORSCHE, 1.122462, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_MAVERICK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_HELICOPTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_VW_VAN_P, SND_BANK_GENRL_VW_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BMW328, 0.84089643, 3, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.65f, 1.3348398, eAEVehicleHornType::CHEVY56, 0.9438743, 3, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_VAN, 3.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.85f, 1.f, eAEVehicleHornType::JEEP, 1.f, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_RC_HELI_P, SND_BANK_GENRL_RC_HELI_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_COBRA_P, SND_BANK_GENRL_COBRA_D, 0, 0.9f, 1.f, eAEVehicleHornType::BMW328, 0.9438743, 2, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PONTIAC_P, SND_BANK_GENRL_PONTIAC_D, 0, 0.9f, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 2, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_HEAVY_V8_P, SND_BANK_GENRL_HEAVY_V8_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 0.9438743, 1, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_B, 0.9438743, 2, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_PORSCHE_P, SND_BANK_GENRL_PORSCHE_D, 1, 0.9f, 1.f, eAEVehicleHornType::BUS_A, 1.f, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.7f, 1.f, eAEVehicleHornType::PICKUP, 1.1892071, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.65f, 1.f, eAEVehicleHornType::BUS_A, 1.1892071, 0, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_CAMPER_VAN, 0.0},
    {AE_BMX, SND_BANK_GENRL_BICYCLE_P, SND_BANK_GENRL_BICYCLE_D, 2, 0.7f, 1.f, eAEVehicleHornType::BIKE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_BICYCLE, 0.0},
    {AE_BMX, SND_BANK_GENRL_BICYCLE_P, SND_BANK_GENRL_BICYCLE_D, 2, 0.7f, 1.f, eAEVehicleHornType::BIKE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_BICYCLE, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_TWINPROP, SND_BANK_GENRL_TWINPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_SINGLEPROP, SND_BANK_GENRL_FASTPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_FASTPROP, SND_BANK_GENRL_FASTPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.85f, 1.f, eAEVehicleHornType::TRUCK, 0.79370052, 3, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_RIG, 6.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.77999997, 1.f, eAEVehicleHornType::TRUCK, 0.84089643, 3, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_RIG, 6.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 1.2599211, 2, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PORSCHE, 1.122462, 2, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 0.7f, 1.f, eAEVehicleHornType::BMW328, 1.f, 1, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.85f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.77999997, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_BIKE, SND_BANK_GENRL_RS427_P, SND_BANK_GENRL_RS427_D, 2, 0.77999997, 1.0594631, eAEVehicleHornType::PICKUP, 1.2599211, -1, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_BIKE, SND_BANK_GENRL_SPORTSBIKE_P, SND_BANK_GENRL_SPORTSBIKE_D, 2, 0.65f, 1.f, eAEVehicleHornType::JEEP, 1.1892071, -1, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_BIKE, SND_BANK_GENRL_COPBIKE_P, SND_BANK_GENRL_COPBIKE_D, 2, 0.9f, 1.f, eAEVehicleHornType::JEEP, 1.f, -1, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_BIKE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.65f, 1.f, eAEVehicleHornType::BUS_A, 0.9438743, 3, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 1.f, 4, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BMW328, 0.9438743, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PORSCHE, 1.f, 2, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.1892071, eAEVehicleHornType::BUS_B, 0.9438743, 4, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 1.1892071, 2, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_FORKLIFT_P, SND_BANK_GENRL_FORKLIFT_D, 2, 1.f, 1.f, eAEVehicleHornType::ESCORT, 1.0594631, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_FORKLIFT, 0.0},
    {AE_CAR, SND_BANK_GENRL_MODEL_T_P, SND_BANK_GENRL_MODEL_T_D, 2, 0.65f, 1.f, eAEVehicleHornType::PICKUP, 0.8908987, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_TRACTOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_HARVESTER_P, SND_BANK_GENRL_HARVESTER_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 0.84089643, 0, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_COMBINE_HARVESTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 0.85f, 1.f, eAEVehicleHornType::CHEVY56, 1.1892071, 2, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_CONVERTIBLE, 0.0},
    {AE_CAR, SND_BANK_GENRL_CADILLAC_P, SND_BANK_GENRL_CADILLAC_D, 0, 0.9f, 1.f, eAEVehicleHornType::BMW328, 1.0594631, 1, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_CAR, SND_BANK_GENRL_HOTROD_P, SND_BANK_GENRL_HOTROD_D, 0, 1.f, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 2, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 0.9f, 1.f, eAEVehicleHornType::CHEVY56, 1.1892071, 1, 1, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_TRAIN, SND_BANK_GENRL_TRAIN_P, SND_BANK_GENRL_TRAIN_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 3, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_TRAIN, 0.0},
    {AE_TRAIN, SND_BANK_GENRL_TRAIN_P, SND_BANK_GENRL_TRAIN_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 3, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_TRAIN, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_HOVERCRAFT_P, SND_BANK_GENRL_HOVERCRAFT_D, 0, 0.85f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_HOVERCRAFT, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.85f, 1.f, eAEVehicleHornType::BMW328, 0.9438743, 2, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BELAIR_P, SND_BANK_GENRL_BELAIR_D, 1, 1.f, 1.1892071, eAEVehicleHornType::CHEVY56, 1.2599211, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 0.65f, 1.f, eAEVehicleHornType::PICKUP, 1.1892071, 1, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PICKUP, 1.0594631, 1, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_PICK_UP, 0.0},
    {AE_CAR, SND_BANK_GENRL_MACKTRUCK_P, SND_BANK_GENRL_MACKTRUCK_D, 0, 0.7f, 1.f, eAEVehicleHornType::TRUCK, 0.9438743, 3, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_FIRETRUCK, 5.0},
    {AE_CAR, SND_BANK_GENRL_HOTROD_P, SND_BANK_GENRL_HOTROD_D, 0, 0.85f, 1.f, eAEVehicleHornType::PORSCHE, 0.9438743, 1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BMW328, 0.8908987, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.7f, 1.f, eAEVehicleHornType::ESCORT, 0.9438743, 2, 0, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_APACHE, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.65f, 1.f, eAEVehicleHornType::CHEVY56, 0.9438743, 1, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.7f, 1.f, eAEVehicleHornType::PORSCHE, 0.9438743, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.77999997, 1.f, eAEVehicleHornType::JEEP, 0.84089643, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.65f, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 4, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_TWINPROP, SND_BANK_GENRL_TWINPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.85f, 1.f, eAEVehicleHornType::PICKUP, 1.0594631, 2, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PICK_UP, 0.0},
    {AE_CAR, SND_BANK_GENRL_PONTIAC_P, SND_BANK_GENRL_PONTIAC_D, 0, 0.77999997, 1.f, eAEVehicleHornType::CHEVY56, 1.2599211, 1, 0, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_HEAVY_V8_P, SND_BANK_GENRL_HEAVY_V8_D, 1, 0.9f, 1.1892071, eAEVehicleHornType::TRUCK, 1.0594631, 2, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_MONSTER_TRUCK, 6.0},
    {AE_CAR, SND_BANK_GENRL_HEAVY_V8_P, SND_BANK_GENRL_HEAVY_V8_D, 1, 0.9f, 1.1892071, eAEVehicleHornType::TRUCK, 1.122462, 2, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_MONSTER_TRUCK, 6.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.85f, 1.f, eAEVehicleHornType::PORSCHE, 1.0594631, 2, 2, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 1, 0.9f, 1.f, eAEVehicleHornType::BMW328, 1.122462, 2, 2, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 1.f, 1.f, eAEVehicleHornType::PICKUP, 1.1892071, 2, 2, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BMW328, 1.0594631, 2, 2, RADIO_DISCO_FUNK, AE_RT_CIVILIAN, AE_VAT_STATION_WAGON, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.85f, 1.f, eAEVehicleHornType::BMW328, 1.122462, 2, 2, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_TWO_DOOR, 0.0},
    {AE_AIRCRAFT_HELICOPTER, SND_BANK_GENRL_APACHE, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_HELICOPTER, 0.0},
    {AE_SPECIAL, SND_BANK_GENRL_RC_TANK_P, SND_BANK_GENRL_RC_TANK_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 0.9f, 1.f, eAEVehicleHornType::CHEVY56, 1.2599211, 2, 2, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 0.85f, 1.f, eAEVehicleHornType::BMW328, 0.9438743, 2, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_CUTLASS_P, SND_BANK_GENRL_CUTLASS_D, 0, 0.9f, 1.f, eAEVehicleHornType::PICKUP, 0.9438743, 1, 1, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_CAR, SND_BANK_GENRL_RS427_P, SND_BANK_GENRL_RS427_D, 0, 0.7f, 1.f, eAEVehicleHornType::PICKUP, 1.2599211, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_BUGGY, 0.0},
    {AE_TRAIN, SND_BANK_GENRL_TRAIN_P, SND_BANK_GENRL_TRAIN_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_TRAIN, SND_BANK_GENRL_TRAIN_P, SND_BANK_GENRL_TRAIN_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_GOKART_P, SND_BANK_GENRL_GOKART_D, 2, 0.77999997, 1.f, eAEVehicleHornType::ESCORT, 1.122462, -1, 0, RADIO_MODERN_ROCK, AE_RT_CIVILIAN, AE_VAT_KART, 0.0},
    {AE_CAR, SND_BANK_GENRL_GOKART_P, SND_BANK_GENRL_GOKART_D, 2, 0.9f, 1.f, eAEVehicleHornType::ESCORT, 0.9438743, -1, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_MOWER, 0.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.1892071, eAEVehicleHornType::BUS_A, 0.8908987, 3, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_SWEEPER_P, SND_BANK_GENRL_SWEEPER_D, 2, 0.85f, 1.f, eAEVehicleHornType::BUS_B, 1.1892071, 4, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_CADILLAC_P, SND_BANK_GENRL_CADILLAC_D, 0, 0.9f, 1.f, eAEVehicleHornType::BMW328, 0.8908987, 1, 1, RADIO_RARE_GROOVE, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_CAR, SND_BANK_GENRL_BELAIR_P, SND_BANK_GENRL_BELAIR_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BUS_B, 1.122462, 1, 1, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_LOWRIDER, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUS_P, SND_BANK_GENRL_BUS_D, 0, 0.77999997, 1.f, eAEVehicleHornType::BUS_A, 0.84089643, 3, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_TRUCK, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PICKUP, 1.f, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_OFFROAD, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 1, 0.85f, 1.f, eAEVehicleHornType::CHEVY56, 0.8908987, 2, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_BIKE, SND_BANK_GENRL_SPORTSBIKE_P, SND_BANK_GENRL_SPORTSBIKE_D, 2, 0.77999997, 1.f, eAEVehicleHornType::JEEP, 0.8908987, -1, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 1.0594631, 4, 0, RADIO_TALK, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_AIRPORT_P, SND_BANK_GENRL_AIRPORT_D, 2, 0.65f, 1.f, eAEVehicleHornType::ESCORT, 0.84089643, 4, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_SPECIAL, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 3, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.77999997, 1.f, eAEVehicleHornType::PORSCHE, 1.f, 2, 0, RADIO_NEW_JACK_SWING, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_BIKE, SND_BANK_GENRL_COPBIKE_P, SND_BANK_GENRL_COPBIKE_D, 2, 0.30000001, 0.8908987, eAEVehicleHornType::PICKUP, 1.1892071, -1, 0, RADIO_COUNTRY, AE_RT_CIVILIAN, AE_VAT_BIKE, 0.0},
    {AE_CAR, SND_BANK_GENRL_90S_P, SND_BANK_GENRL_90S_D, 0, 0.85f, 1.f, eAEVehicleHornType::BUS_B, 1.2599211, 2, 0, RADIO_REGGAE, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_CAR, SND_BANK_GENRL_VW_VAN_P, SND_BANK_GENRL_VW_VAN_D, 0, 0.65f, 1.f, eAEVehicleHornType::BUS_A, 0.9438743, 4, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_MUSTANG_P, SND_BANK_GENRL_MUSTANG_D, 0, 1.f, 1.f, eAEVehicleHornType::JEEP, 0.9438743, 2, 0, RADIO_HOUSE_CLASSICS, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_TRAIN, SND_BANK_GENRL_TRAIN_P, SND_BANK_GENRL_TRAIN_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_SPECIAL, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_SPECIAL, AE_VAT_NONE, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_NONE, 0.0},
    {AE_AIRCRAFT_PLANE, SND_BANK_GENRL_SINGLEPROP, SND_BANK_GENRL_FASTPROP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, 0, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PLANE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_BOAT, SND_BANK_GENRL_BOAT_INBOARD_P, SND_BANK_GENRL_BOAT_INBOARD_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_BOAT, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 1.0594631, 2, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.7f, 1.f, eAEVehicleHornType::CHEVY56, 1.0594631, 2, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_MERC_P, SND_BANK_GENRL_MERC_D, 0, 0.7f, 1.f, eAEVehicleHornType::PICKUP, 1.0594631, 2, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PATHFINDER_P, SND_BANK_GENRL_PATHFINDER_D, 0, 0.7f, 1.f, eAEVehicleHornType::BUS_A, 1.0594631, 2, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BUICK_P, SND_BANK_GENRL_BUICK_D, 0, 0.7f, 1.f, eAEVehicleHornType::PICKUP, 1.122462, 2, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_PICK_UP, 0.0},
    {AE_CAR, SND_BANK_GENRL_JALOPY_P, SND_BANK_GENRL_JALOPY_D, 0, 0.7f, 1.f, eAEVehicleHornType::TRUCK, 0.9438743, 3, 0, RADIO_OFF, AE_RT_EMERGENCY, AE_VAT_POLICE_VAN, 0.0},
    {AE_CAR, SND_BANK_GENRL_COBRA_P, SND_BANK_GENRL_COBRA_D, 0, 0.85f, 1.f, eAEVehicleHornType::BMW328, 1.f, 2, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_COUPE, 0.0},
    {AE_CAR, SND_BANK_GENRL_PONTIAC_P, SND_BANK_GENRL_PONTIAC_D, 0, 0.9f, 1.f, eAEVehicleHornType::PORSCHE, 1.0594631, 1, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_SPORTS_CAR, 0.0},
    {AE_CAR, SND_BANK_GENRL_BELAIR_P, SND_BANK_GENRL_BELAIR_D, 0, 0.65f, 1.f, eAEVehicleHornType::BUS_B, 1.0594631f, 1, 0, RADIO_CLASSIC_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_FOUR_DOOR, 0.0},
    {AE_CAR, SND_BANK_GENRL_PACARD_P, SND_BANK_GENRL_PACARD_D, 0, 0.65f, 1.f, eAEVehicleHornType::PICKUP, 1.0594631f, 1, 0, RADIO_CLASSIC_ROCK, AE_RT_CIVILIAN, AE_VAT_PICK_UP, 0.0},
    {AE_NO_VEHICLE, SND_BANK_GENRL_TEMP_P, SND_BANK_GENRL_TEMP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_GENRL_TEMP_P, SND_BANK_GENRL_TEMP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_GENRL_TEMP_P, SND_BANK_GENRL_TEMP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_GENRL_VAN_P, SND_BANK_GENRL_VAN_D, 0, 0.7f, 1.f, eAEVehicleHornType::BMW328, 0.84089643, -1, 0, RADIO_MODERN_HIP_HOP, AE_RT_CIVILIAN, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_GENRL_TEMP_P, SND_BANK_GENRL_TEMP_D, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_NO_VEHICLE, SND_BANK_UNK, SND_BANK_UNK, 0, 0.7f, 1.f, eAEVehicleHornType::NONE, 1.f, -1, 0, RADIO_OFF, AE_RT_DISABLED, AE_VAT_NONE, 0.0},
    {AE_CAR, SND_BANK_FEET_GENERIC, SND_BANK_FEET_GENERIC, 0, 0.0, 0.0, eAEVehicleHornType::BIKE, 0.0, 0, 0, RADIO_EMERGENCY_AA, AE_RT_SPECIAL, AE_VAT_TWO_DOOR, 2.3694278e-38}
}};
#pragma warning(pop)

inline tVehicleAudioSettings& GetVehicleAudioSettings(eModelID model) {
    return VehicleAudioSettings[model - (+MODEL_VEHICLE_FIRST)];
}
